language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1

install:
  - wget "https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh"
  - ./dotnet-install.ps1 -Architecture x64 -Version '5.0.100-preview.7.20366.6'

script:
  - https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh
  - ./build.sh --target=Travis --configuration=Release
