language: csharp
os: linux
dist: xenial
mono: none
dotnet: 3.1

install:
  - wget "https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh"
  - chmod +x dotnet-install.sh
  - sudo ./dotnet-install.sh --version '5.0.100-preview.7.20366.6' --install-dir '/usr/share/dotnet'

script:
  - ./build.sh --target=Travis --configuration=Release
