image: Visual Studio 2019

install:
- ps: |
    $env:CORE_SDK_VERSION = '5.0.100-preview.7'
    Write-Host "Installing .NET Core SDK $env:CORE_SDK_VERSION"
    Invoke-WebRequest -Uri 'https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version $env:CORE_SDK_VERSION -InstallDir "$env:ProgramFiles\dotnet"

build_script: 
  - ps: .\build.ps1 --target=AppVeyor --configuration=release
  
# disable built-in tests.
test: off

artifacts:
- path: package\*.zip
- path: package\*.nupkg

environment:
  MYGET_API_KEY:
    secure: wtAvJDVl2tfwiVcyLExFHLvZVfUWiQRHsfdHBFCNEATeCHo1Nd8JP642PfY8xhji
  NUGET_API_KEY:
    secure: 3ojZLs9hiHk/7047hiirFk/qG2RxUACmA8DAUk+8AoILr5R7c4tDGXeTsBjjhq5h
  CHOCO_API_KEY:
    secure: aDsu1U+umVYFVybjkBVtVQsatSj3QKbD7VkGQci9mNF3493g9Giao/GABISIaHjT
